# open_jpeg target

set(CONAN_INCLUDE_DIRS_OPEN_JPEG_DEBUG ${CONAN_INCLUDE_DIRS_OPEN_JPEG_DEBUG}/LibJPEG/)
set(CONAN_INCLUDE_DIRS_OPEN_JPEG_RELEASE ${CONAN_INCLUDE_DIRS_OPEN_JPEG_RELEASE}/LibJPEG/)
__conan_import(open_jpeg lib)
