macro(__env_target_runtime_dir target_name)
    if(TARGET ${target_name})
        get_target_property(target_type ${target_name} TYPE)
        # __normal_message("Target ${target_name} is an ${target_type} target")

        if(target_type STREQUAL "SHARED_LIBRARY")
            get_target_property(IMPORT_LOC_DEBUG ${target_name} IMPORTED_LOCATION_DEBUG)
            get_target_property(IMPORT_LOC_RELEASE ${target_name} IMPORTED_LOCATION_RELEASE)

            if(IMPORT_LOC_DEBUG)
                get_filename_component(ENV_PATH ${IMPORT_LOC_DEBUG} DIRECTORY)
            endif()
            if(IMPORT_LOC_RELEASE)
                get_filename_component(ENV_PATH ${IMPORT_LOC_RELEASE} DIRECTORY)
            endif()
        endif()
    else()
        __normal_message("Target ${target_name} not found")
    endif()
endmacro()
